### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by paulbellmann** [paulbellmann/djangoBase#4]
- "Forgot Password?"
- maybe over mail

**Comment by akhil117** [comment]
I want work on this issue. Could you give me more information about this one.

**Comment by akhil117** [comment]
I mean I should add forgot password on login page??

**Comment by paulbellmann** [comment]
yea, on the login page. like facebook and co.

**Comment by akhil117** [comment]
Could you review it https://github.com/paulbellmann/ojuice/pull/6.
